### ISSUE TITLE
UnknownNetworkError on Download

### ISSUE THREAD

**Issue by mtrojacher** [DEWETRON/AppUpdate#1]
No Dewetron products installed; clicking on one of the download links leads to "Download error: UnknownNetworkError"

(Default browser: Firefox)

![image](https://user-images.githubusercontent.com/3242018/93772756-82640480-fc1f-11ea-889b-a210b220ebce.png)

**Comment by glaure** [comment]
OpenSSL DLLs were missing in the installer package.
