### ISSUE TITLE
Main Windows scaling

### ISSUE THREAD

**Issue by mtrojacher** [DEWETRON/AppUpdate#2]
Main window size/scaling is off, not all elements are shown after starting the AppUpdate

![image](https://user-images.githubusercontent.com/3242018/93988447-fff75400-fd88-11ea-9606-790a47e6eee8.png)

Display resolution/scaling settings:
![image](https://user-images.githubusercontent.com/3242018/93988521-1bfaf580-fd89-11ea-8cd8-02ce3cb29bd5.png)

**Comment by mtrojacher** [comment]
after switching the main display to one with 100% scaling, the appupdate window is sized correctly

**Comment by glaure** [comment]
Fixed in 8240e9cd30dfef2ab0595bf021469683f3726322
