### ISSUE TITLE
Updating AppUpdate via AppUpdate

### ISSUE THREAD

**Issue by mtrojacher** [DEWETRON/AppUpdate#3]
When downloading and starting the AppUpdate - Update i get prompted if the running application has to be closed:
![image](https://user-images.githubusercontent.com/3242018/94011114-2c21cd80-fda7-11ea-8053-1cff0a7a39ea.png)

This will open the "this app will stay in the systray" notification in the background. only after manually finding and accepting this message, the application will be closed and the update will install.

**Comment by glaure** [comment]
Thats because WM_CLOSE only minimizes a tray icon application and does not close it ...
I will try a workaround.
